sonar.projectKey=ngotuananh101_cloudx
sonar.organization=ngotuananh101

sonar.sources=app,bootstrap/app.php,config,database,resources/js,routes

sonar.exclusions=\
  **/vendor/**,\
  **/node_modules/**,\
  **/storage/**,\
  **/public/build/**,\
  **/tests/**,\
  **/lang/**,\
  **/*.blade.php,\
  resources/js/actions/**,\
  resources/js/routes/**

sonar.php.file.suffixes=php
sonar.javascript.file.suffixes=js,jsx,ts,tsx
